################################        IAM ROLE CFT              ################################
AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: IAM Role for AWS cloud
################################          PARAMETERS              ################################

Parameters:
 ENV:
  Type: String
  Description: env
  Default: prod
 
 LambdaSGID:
  Type: String
  Default: TBD
 
 ApplicationOwner:
  Type: String
  Default: Raghuram

 ApplicationName:
  Type: String
  Default: WordReplacement  
  
 CostID:
  Type: String
  Default: 123A
  
################################          RESOURCES               ################################  
Resources:
################################           IAM                    ################################
    IAMRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: "Raghuramlambda-role-914a4xs"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/service-role/AWSLambdaBasicExecutionRole-39faa9ae-6050-4d65-9759-94256356d366"
              - "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
              - "arn:aws:iam::aws:policy/AmazonRDSFullAccess"